import os
from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

load_dotenv()

# Initialize Gemini LLM
llm = ChatGoogleGenerativeAI(
    model="gemini-1.5-flash",  # Free tier model
    google_api_key=os.getenv("GEMINI_API_KEY"),
    temperature=0.7
)

parser = StrOutputParser()


async def run_rfp_agent(rfp_text: str) -> dict:
    """
    Multi-step AI agent that:
    1. Summarizes the RFP
    2. Identifies key requirements
    3. Drafts each section of the response
    """

    # ── Step 1: Summarize the RFP ──────────────────────────────────────
    summary_prompt = ChatPromptTemplate.from_template("""
    You are an expert business analyst. Read this RFP carefully and provide:
    1. A 3-sentence summary
    2. The client's main goals
    3. Key requirements they are looking for

    RFP TEXT:
    {rfp_text}

    Respond in clear, concise bullet points.
    """)

    summary_chain = summary_prompt | llm | parser
    summary = await summary_chain.ainvoke({"rfp_text": rfp_text[:3000]})


    # ── Step 2: Draft Executive Summary section ────────────────────────
    exec_summary_prompt = ChatPromptTemplate.from_template("""
    You are a professional proposal writer. Write a compelling Executive Summary
    section for an RFP response based on this RFP.

    Keep it to 2-3 paragraphs. Be professional, confident, and client-focused.

    RFP SUMMARY:
    {summary}

    Write only the Executive Summary section.
    """)

    exec_chain = exec_summary_prompt | llm | parser
    executive_summary = await exec_chain.ainvoke({"summary": summary})


    # ── Step 3: Draft Technical Approach section ───────────────────────
    technical_prompt = ChatPromptTemplate.from_template("""
    You are a technical writer. Write a Technical Approach section for an RFP response.
    Describe how your team would deliver the project, what methodology you'd use,
    and why your approach is the best fit.

    Based on this RFP summary:
    {summary}

    Write only the Technical Approach section. Use clear headings and bullet points.
    """)

    tech_chain = technical_prompt | llm | parser
    technical_approach = await tech_chain.ainvoke({"summary": summary})


    # ── Step 4: Draft Timeline & Pricing section ───────────────────────
    timeline_prompt = ChatPromptTemplate.from_template("""
    You are a project manager. Write a proposed Timeline and Pricing section
    for an RFP response. Include realistic phases, milestones, and a note about
    pricing flexibility.

    Based on this RFP summary:
    {summary}

    Write only the Timeline and Pricing section.
    """)

    timeline_chain = timeline_prompt | llm | parser
    timeline = await timeline_chain.ainvoke({"summary": summary})


    # ── Step 5: Combine into full response ─────────────────────────────
    full_response = f"""
# PROPOSAL RESPONSE

## Executive Summary
{executive_summary}

---

## Technical Approach
{technical_approach}

---

## Timeline & Pricing
{timeline}

---

*This proposal was generated by AI and should be reviewed and customized before submission.*
    """.strip()

    return {
        "summary": summary,
        "response": full_response,
        "sections": {
            "executive_summary": executive_summary,
            "technical_approach": technical_approach,
            "timeline": timeline
        }
    }
